### ISSUE TITLE
aws:runInstances BlockDeviceMapping option not working

### ISSUE THREAD

**Issue by tomiszili** [awsdocs/aws-systems-manager-user-guide#204]
Hello!

Please make some examples on the ssm automation actions, e.g.: aws:runInstances.
The BlockDeviceMappings parameter not working at all.
https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-action-runinstance.html

I was tring to make an automation with aws:runInstances automation action with an AMZ2 ami id but changing the root volume from gp2 to gp3.
My automation document step is the following:
```
- name: runec2
    action: 'aws:runInstances'
    inputs:
      ImageId: ami-06c39ed6b42908a36
      BlockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            deleteOnTermination: true
            encrypted: true
            volumeType: gp3
    description: runec2
```
And when I executed the automation document the console shows the following input parameters for this step:
```
BlockDeviceMappings
[{"deviceName":null,"virtualName":null,"ebs":null,"noDevice":null}]
ImageId
"ami-06c39ed6b42908a36"
```
What am i doing wrong?

Thanks in advance!
